name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event_name == 'push' && 'development' || inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && 'development' || inputs.environment }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm -r lint

      - name: Test
        run: pnpm -r test

      - name: Build
        run: pnpm -r build

      - name: Deploy to develop
        if: github.event_name == 'push'
        run: echo "Deploying to DEVELOPMENT environment"

      - name: Deploy to staging
        if: github.event_name == 'workflow_dispatch' && inputs.environment == 'staging'
        run: echo "Deploying to STAGING environment"

      - name: Deploy to production
        if: github.event_name == 'workflow_dispatch' && inputs.environment == 'prod'
        run: echo "Deploying to PRODUCTION environment"

      - name: Post-deployment verification
        run: |
          echo "Verifying deployment..."
          echo "Deployment to ${{ github.event_name == 'push' && 'development' || inputs.environment }} completed successfully!"
